name: speed_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # PDF Rendering
  pdfx: ^2.7.0
  
  # PDF Text Extraction
  syncfusion_flutter_pdf: ^28.1.33
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # File Handling
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  
  # Storage
  shared_preferences: ^2.3.3
  
  # Utilities
  equatable: ^2.0.7
  path: ^1.9.1
  uuid: ^4.5.2
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default:21


flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
